doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        options:
            !php/const \PDO::MYSQL_ATTR_LOCAL_INFILE: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            ShortenerConnector:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Shortener\Entity'
                alias: Shortener
