version: '3.7'

services:
    fpm:
        networks:
            - shortener-network
        hostname: fpm
        container_name: shortener-fpm
        restart: always
        build:
            args:
                var: var

    nginx:
        image: nginx:1.22.1
        container_name: shortener-frontend
        environment:
            shortener: shortener
            VIRTUAL_HOST: shortener.local
        networks:
            - shortener-network
            - nginx-proxy
        volumes:
            - shortener_public_data:/var/www/public
            - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
        restart: always
        depends_on:
            - fpm

volumes:
    shortener_public_data:

networks:
    shortener-network:
        name: shortener-network
    nginx-proxy:
        name: nginx-proxy
